# -*- coding: utf-8 -*-
"""hangman.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X5tH-2xGdOjn48wR1_qbvp7Tl02_mm1W
"""

import random

words = ["apple", "tiger", "chair", "robot", "plant"]
chosen_word = random.choice(words)

display = ["_"] * len(chosen_word)
guessed_letters = []
attempts = 6

print("🎮 Hangman Game Started!\n")

while attempts > 0 and "_" in display:
    print("-" * 30)
    print("Word:", " ".join(display))
    print("Guessed letters:", ", ".join(guessed_letters))
    print("Attempts left:", attempts)

    guess = input("Enter a letter: ").strip().lower()

    if len(guess) != 1 or not guess.isalpha():
        print("⚠️ Invalid input. Try again.\n")
        continue

    if guess in guessed_letters:
        print("⚠️ Already guessed.\n")
        continue

    guessed_letters.append(guess)

    if guess in chosen_word:
        for i in range(len(chosen_word)):
            if chosen_word[i] == guess:
                display[i] = guess
        print("✅ Correct!\n")
    else:
        attempts -= 1
        print("❌ Wrong!\n")

print("-" * 30)

if "_" not in display:
    print("🎉 You won! Word:", chosen_word)
else:
    print("💀 You lost! Word was:", chosen_word)